### Load in NumPy (remember to pip install numpy first)

In [2]:
import numpy as np, random

### The Basics

In [ ]:
a = np.array([1,6,2,3,2], dtype='int32')
ix, = np.where(a>2)
print(a, ix)

[1 6 2 3 2] [1 3]


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
b[[0, 1, 1], [2, 0, 2]] # indices filter, row idx list first, then col idx list, but same length, when match row & col, it gets ele @ (0, 2), (1, 0), (0, 2)

array([7., 6., 4.])

In [ ]:
a[:3].dot(b[0])

71.0

In [ ]:
# Get Dimension
a.ndim

1

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
# Get Type
a.dtype

dtype('int32')

In [ ]:
# Get Size, bit size, 4 bytes here
a.itemsize

4

In [ ]:
# Get total size
a.nbytes

20

In [ ]:
# Get number of elements
a.size

5

In [ ]:
# np linespace
a = np.linspace(-1, 1, 20) # last is num=, so that is num points, but num-1 divisions
a

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [ ]:
a[[2, 3, 6, 8]] # filter by indices

array([-0.78947368, -0.68421053, -0.36842105, -0.15789474])

In [ ]:
sum(a[[2, 3, 6]])

-1.842105263157895

In [ ]:
# np clip, make list in range, any bigger than max replaced with max, smaller than min replaced with min
a = np.arange(10)
np.clip(a, 1, 8)

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 8])

### Accessing/Changing specific elements, rows, columns, etc

In [ ]:
a = np.array([[1,-2,3,4,-5,6,7],[8,-9,10,11,-12,13,14]], dtype=np.float32)
# a[a<0] = 0.1 # replace with value
a = np.where(a<0, a*0.1, a)
a

array([[ 1.        , -0.2       ,  3.        ,  4.        , -0.5       ,
         6.        ,  7.        ],
       [ 8.        , -0.90000004, 10.        , 11.        , -1.2       ,
        13.        , 14.        ]], dtype=float32)

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific element [r, c]
a[1, 5]

13

In [ ]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)
b[0,1,1]

4

In [ ]:
# replace
# b[:,1,:] = [[9,9,9],[8,8]]
print(b[:,1,:])
b[:,1,:] = [[9,9],[8,8]]
b[:,1,:]

[[3 4]
 [7 8]]


array([[9, 9],
       [8, 8]])

In [ ]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2,3))
# np.zeros(5)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

In [ ]:
# Any other number
np.full((2,2), 99)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -4, -4],
       [ 6,  6,  3],
       [ 3,  2,  2]])

In [ ]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


### Basic math

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([5, 6, 7, 8])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [ ]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [ ]:
a = np.ones((5,3))
b = np.full((3, 2), 5)
a.dot(b), a, b

In [ ]:
a = np.ones((2,3))
print(a)
# b = np.random.rand(3,2)
# np.random.randint(5, size=5) # one dimnb=

np.random.randint(5, size=(3, 2))
# b = np.full((3,2), random.randint(1, 10))
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0.53074217 0.33368159]
 [0.98303671 0.06910728]
 [0.35140661 0.91130156]]


array([[1.86518549, 1.31409043],
       [1.86518549, 1.31409043]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before, '\n')

# after = before.reshape((2,3)) # valueError reshape
after = before.reshape((2, -1, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [ ]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## np flip

In [ ]:
X = np.arange(8).reshape((2,2,2))
X

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.flip(X, 1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [ ]:
np.fliplr(X) # this is confusing, better use flip with dimension input, similar flipeud. Unless just 2D

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [ ]:
np.flip(X, (0, 2))

array([[[5, 4],
        [7, 6]],

       [[1, 0],
        [3, 2]]])

In [ ]:
## test flip diagonal
X = np.arange(8).reshape(2, 4)
X

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.fliplr(np.flipud(X))

array([[7, 6, 5, 4],
       [3, 2, 1, 0]])

## lexsort

In [ ]:
# prompt: np lexsort example

# ## lexsort
a = [1, 5, 1, 4, 3, 4, 4] # if tie on first key, move to second key
b = [9, 4, 0, 4, 0, 2, 1]
ind = np.lexsort((b, a)) # sort by a, then by b
[(a[i], b[i]) for i in ind]


[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

In [ ]:
# prompt: lexsort 3x3x3 float example

a = np.random.rand(3, 3, 3)
b = np.random.rand(3, 3, 3)
c = np.random.rand(3, 3, 3)
ind = np.lexsort((a.flatten(), b.flatten(), c.flatten()))
[(a.flatten()[i], b.flatten()[i], c.flatten()[i]) for i in ind]


In [ ]:
names = ['Bob', 'Alice', 'Charlie', 'Bob', 'David']
scores = [85, 92, 78, 95, 70]

# Sort by score first, then by name
indices = np.lexsort((names, scores)); print(indices)

# sorted_scores = scores[indices] # both scores and names are list, not np.aray, can't do this
# sorted_names = names[indices]
# sorted_scores = [scores[i] for i in indices]
# sorted_names = [names[i] for i in indices]

# or convert to np.array, then use indices
sorted_scores = np.array(scores)[indices]
sorted_names = np.array(names)[indices]

print(sorted_scores)
print(sorted_names)


[4 2 0 1 3]
[70 78 85 92 95]
['David' 'Charlie' 'Bob' 'Alice' 'Bob']


## allclose, determine if two arrays are element-wise equal within a specified tolerance

In [6]:
# prompt: np.allclose example, rtol: Relative tolerance, atol: Absolute tolerance

a = np.array([1e10,1e-7])
b = np.array([1.00001e10,1e-8])
equal = np.allclose(a, b) # default rtol=1e-05, atol=1e-08
print(equal)
equal = np.allclose(a, b, rtol=1e-5, atol=1e-7)
print(equal)


False
True
